`ndarray` -> Array class
`a.shape` -> Returns (columns, rows)
`a.ndim` -> Returns dimension
`a.size` -> Returns no. of elements
`a.dtype` -> Returns type of elements

In [1]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a)
print(type(a))

print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
int64
6
2


`np.zeros()` -> Array with only 0s
`np.ones()` -> Array with only 1s
`np.empty()` -> Array with random content.
`np.arange(first_num, last_num, step)` -> Array with a range of elements
`np.linspace(first_num, last_num, step)` -> Array with values spaced linearly

> Note
> Default `dtype` is `np.float64`. Use `dtype` keyword to specify

In [2]:
print("Ones")
print(np.ones([2,3]))
print(np.ones(5))
print(np.ones([6,7]))

print("Zeroes")
print(np.zeros(10))
print(np.empty(3))

print("Range")
print(np.arange(5))
print(np.arange(1,5))
print(np.arange(1,6,2))
print(np.linspace(0, 20, num=5))

Ones
[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
Zeroes
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0.]
Range
[0 1 2 3 4]
[1 2 3 4]
[1 3 5]
[ 0.  5. 10. 15. 20.]
