1 - Addition of 2 vectors

In [9]:
import numpy as np

def add_vectors(v,w):
    return [v[i] + w[i] for i in range(len(v))]

a = np.array([[2,-1], [4,0]])
print(a)
b = np.array([[1,3], [2,4]])
print(b)
print(add_vectors(a,b))

[[ 2 -1]
 [ 4  0]]
[[1 3]
 [2 4]]
[array([3, 2]), array([6, 4])]


2 - Subtraction of 2 vectors

In [18]:
import numpy as np

def subtract_vectors(v,w):
    return [v[i] - w[i] for i in range(len(v))]

a = np.array([[2,-1], [4,0]])
print(a)
b = np.array([[1,3], [2,4]])
print(b)
print(subtract_vectors(a,b))

[[ 2 -1]
 [ 4  0]]
[[1 3]
 [2 4]]
[array([ 1, -4]), array([ 2, -4])]
